name: Build and Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.example .env

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Show containers
        run: docker compose ps

      - name: Test users route
        run: curl -f http://localhost:8000/users

      - name: Test posts route
        run: curl -f http://localhost:8000/posts

      - name: Stop containers
        if: always()
        run: docker compose down -v
