name: Build and Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image for scanning
        run: docker build -t api-image:1.0.0 -f ./api/Dockerfile ./api

      - name: Docker Scout Scan API
        continue-on-error: true
        uses: docker/scout-action@v1
        with:
          command: cves
          image: local://api-image:1.0.0
          file: ./api/Dockerfile
          only-severities: critical
          exit-code: false

      - name: Build Mongo image for scanning
        run: docker build -t mongo-image:1.0.0 -f ./mongo/Dockerfile ./mongo

      - name: Docker Scout Scan Mongo
        continue-on-error: true
        uses: docker/scout-action@v1
        with:
          command: cves
          image: local://mongo-image:1.0.0
          file: ./mongo/Dockerfile
          only-severities: critical,high
          exit-code: false

      - name: Build the stack
        run: docker compose up -d --build
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ynov_ci
          MYSQL_USER: admin
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          MONGO_DATABASE: blog_db
          ME_CONFIG_BASICAUTH_USERNAME: admin
          ME_CONFIG_BASICAUTH_PASSWORD: ${{ secrets.ME_CONFIG_BASICAUTH_PASSWORD }}

      - name: Check containers health
        run: ./scripts/check-health.sh

      - name: Test users route
        run: curl -f http://localhost:8000/users

      - name: Test posts route
        run: curl -f http://localhost:8000/posts

      - name: Push API image
        run: |
          docker tag api-image:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/mongo-api-mysql-api:1.0.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mongo-api-mysql-api:1.0.0

      - name: Push Mongo image
        run: |
          docker tag mongo-image:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/mongo-api-mysql-mongo:1.0.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mongo-api-mysql-mongo:1.0.0

      - name: Stop containers
        if: always()
        run: docker compose down -v
