name: Build and Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image for scanning
        run: docker build -t api-image:1.0.0 -f ./api/Dockerfile ./api

      - name: Docker Scout Scan API
        uses: docker/scout-action@v1
        with:
          command: cves, recommendation
          image: api-image:1.0.0
          file: ./api/Dockerfile
          only-severities: critical,high
          exit-code: true

      - name: Build Mongo image for scanning
        run: docker build -t mongo-image:1.0.0 -f ./Init/Dockerfile ./mongo

      - name: Docker Scout Scan Mongo
        uses: docker/scout-action@v1
        with:
          command: cves, recommendation
          image: mongo-image:1.0.0
          file: ./mongo/Dockerfile
          only-severities: critical,high
          exit-code: true

      - name: Create .env file
        run: cp .env.example .env

      - name: Build the stack
        run: docker compose up -d

      - name: Wait for services
        run: sleep 30

      - name: Show containers status
        run: docker compose ps

      - name: Test users route
        run: curl -f http://localhost:8000/users

      - name: Test posts route
        run: curl -f http://localhost:8000/posts

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag API image
        run: docker tag api-image:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/mongo-api-mysql-api:latest

      - name: Tag Mongo image
        run: docker tag mongo-image:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/mongo-api-mysql-mongo:latest

      - name: Push API image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mongo-api-mysql-api:latest

      - name: Push Mongo image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mongo-api-mysql-mongo:latest

      - name: Stop containers
        if: always()
        run: docker compose down -v
